version: '3.8'

services:
  frontend-admin:
    build: ./frontend-admin
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
    command: npm start

  frontend-user:
    build: ./frontend-user
    ports:
      - "3001:3000"
    volumes:
      - ./frontend-user:/app
      - /app/node_modules
    command: npm start